-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 17:27:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EQUIPOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EQUIPOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EQUIPOS` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema HISTORIAN
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HISTORIAN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HISTORIAN` ;
-- -----------------------------------------------------
-- Schema ALINEACION
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ALINEACION
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ALINEACION` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema LABORATORIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LABORATORIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LABORATORIO` ;
-- -----------------------------------------------------
-- Schema PERSONAL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PERSONAL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PERSONAL` ;
-- -----------------------------------------------------
-- Schema INSUMOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema INSUMOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INSUMOS` ;
-- -----------------------------------------------------
-- Schema OPERACIONES
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BALANCE_PLANTA
-- -----------------------------------------------------
USE `EQUIPOS` ;

-- -----------------------------------------------------
-- Table `EQUIPOS`.`ClaseEquipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EQUIPOS`.`ClaseEquipo` (
  `clase` VARCHAR(45) NOT NULL COMMENT 'Corresponde al tipo de equipo que estamos viendo. Es una clasificación que cuenta con opciones como decantadores, espesadores, centrífugas, cámaras, lineas, etc...\n\nPermitirá a futuro definir las operaciones de cada equipo permitiendo así la automatización del balance de planta.',
  PRIMARY KEY (`clase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EQUIPOS`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EQUIPOS`.`Area` (
  `numero` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EQUIPOS`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EQUIPOS`.`Equipo` (
  `tag` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clase` VARCHAR(45) NOT NULL,
  `area` INT NOT NULL,
  PRIMARY KEY (`tag`),
  INDEX `fk_Equipo_ClaseEquipo_idx` (`clase` ASC) VISIBLE,
  INDEX `fk_Equipo_Area1_idx` (`area` ASC) VISIBLE,
  CONSTRAINT `fk_Equipo_ClaseEquipo`
    FOREIGN KEY (`clase`)
    REFERENCES `EQUIPOS`.`ClaseEquipo` (`clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Area1`
    FOREIGN KEY (`area`)
    REFERENCES `EQUIPOS`.`Area` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EQUIPOS`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EQUIPOS`.`Sensor` (
  `tagSensor` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `dimensión` VARCHAR(45) NULL COMMENT 'Atributo que define las unidades en las que se contine la instancia de los datos rescatados.',
  `Equipo_tag` VARCHAR(45) NULL,
  PRIMARY KEY (`tagSensor`),
  INDEX `fk_Sensor_Equipo1_idx` (`Equipo_tag` ASC) VISIBLE,
  CONSTRAINT `fk_Sensor_Equipo1`
    FOREIGN KEY (`Equipo_tag`)
    REFERENCES `EQUIPOS`.`Equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EQUIPOS`.`PuntoMuestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EQUIPOS`.`PuntoMuestra` (
  `idPuntoMuestra` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `Equipo_tag` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuntoMuestra`),
  INDEX `fk_PuntoMuestra_Equipo1_idx` (`Equipo_tag` ASC) VISIBLE,
  CONSTRAINT `fk_PuntoMuestra_Equipo1`
    FOREIGN KEY (`Equipo_tag`)
    REFERENCES `EQUIPOS`.`Equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `HISTORIAN` ;

-- -----------------------------------------------------
-- Table `HISTORIAN`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HISTORIAN`.`Sensor` (
  `tagSensor` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `dimensión` VARCHAR(45) NULL COMMENT 'Atributo que define las unidades en las que se contine la instancia de los datos rescatados.',
  `Equipo_tag` VARCHAR(45) NULL,
  PRIMARY KEY (`tagSensor`),
  INDEX `fk_Sensor_Equipo1_idx` (`Equipo_tag` ASC) VISIBLE,
  CONSTRAINT `fk_Sensor_Equipo1`
    FOREIGN KEY (`Equipo_tag`)
    REFERENCES `EQUIPOS`.`Equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HISTORIAN`.`Fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HISTORIAN`.`Fecha` (
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HISTORIAN`.`ValorHistorian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HISTORIAN`.`ValorHistorian` (
  `fecha` DATE NOT NULL,
  `tagSensor` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,3) NULL,
  PRIMARY KEY (`fecha`, `tagSensor`),
  INDEX `fk_ValorHistorian_Fecha1_idx` (`fecha` ASC) VISIBLE,
  CONSTRAINT `fk_ValorHistorian_Sensor1`
    FOREIGN KEY (`tagSensor`)
    REFERENCES `HISTORIAN`.`Sensor` (`tagSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ValorHistorian_Fecha1`
    FOREIGN KEY (`fecha`)
    REFERENCES `HISTORIAN`.`Fecha` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ALINEACION` ;

-- -----------------------------------------------------
-- Table `ALINEACION`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`Area` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALINEACION`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`equipo` (
  `tag` VARCHAR(45) NOT NULL,
  `numeroArea` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`tag`),
  INDEX `fk_equipo_Area1_idx` (`numeroArea` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_Area1`
    FOREIGN KEY (`numeroArea`)
    REFERENCES `ALINEACION`.`Area` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALINEACION`.`TipoSalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`TipoSalida` (
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALINEACION`.`Salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`Salida` (
  `linea` INT NOT NULL,
  PRIMARY KEY (`linea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALINEACION`.`Fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`Fecha` (
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALINEACION`.`LineSalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`LineSalida` (
  `lineaSalida` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lineaSalida`, `tipo`),
  INDEX `fk_TipoSalida_has_Salida_Salida1_idx` (`lineaSalida` ASC) VISIBLE,
  INDEX `fk_TipoSalida_has_Salida_TipoSalida1_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_TipoSalida_has_Salida_TipoSalida1`
    FOREIGN KEY (`tipo`)
    REFERENCES `ALINEACION`.`TipoSalida` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoSalida_has_Salida_Salida1`
    FOREIGN KEY (`lineaSalida`)
    REFERENCES `ALINEACION`.`Salida` (`linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALINEACION`.`equipo_has_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ALINEACION`.`equipo_has_equipo` (
  `fecha` DATE NOT NULL,
  `tagOrigen` VARCHAR(45) NOT NULL,
  `tagSalida` VARCHAR(45) NOT NULL,
  `lineaSalida` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`, `tagOrigen`, `tagSalida`, `lineaSalida`, `tipo`),
  INDEX `fk_equipo_has_equipo_equipo2_idx` (`tagSalida` ASC) VISIBLE,
  INDEX `fk_equipo_has_equipo_equipo1_idx` (`tagOrigen` ASC) VISIBLE,
  INDEX `fk_equipo_has_equipo_Fecha1_idx` (`fecha` ASC) VISIBLE,
  INDEX `fk_equipo_has_equipo_LineSalida1_idx` (`lineaSalida` ASC, `tipo` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_has_equipo_equipo1`
    FOREIGN KEY (`tagOrigen`)
    REFERENCES `ALINEACION`.`equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_has_equipo_equipo2`
    FOREIGN KEY (`tagSalida`)
    REFERENCES `ALINEACION`.`equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_has_equipo_Fecha1`
    FOREIGN KEY (`fecha`)
    REFERENCES `ALINEACION`.`Fecha` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_has_equipo_LineSalida1`
    FOREIGN KEY (`lineaSalida` , `tipo`)
    REFERENCES `ALINEACION`.`LineSalida` (`lineaSalida` , `tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `LABORATORIO` ;

-- -----------------------------------------------------
-- Table `LABORATORIO`.`PuntoMuestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`PuntoMuestra` (
  `idPuntoMuestra` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `Equipo_tag` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuntoMuestra`),
  INDEX `fk_PuntoMuestra_Equipo1_idx` (`Equipo_tag` ASC) VISIBLE,
  CONSTRAINT `fk_PuntoMuestra_Equipo1`
    FOREIGN KEY (`Equipo_tag`)
    REFERENCES `EQUIPOS`.`Equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PERSONAL`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSONAL`.`Area` (
  `idArea` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PERSONAL`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSONAL`.`Cargo` (
  `idCargo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`),
  INDEX `fk_Cargo_Area_idx` (`area` ASC) VISIBLE,
  CONSTRAINT `fk_Cargo_Area`
    FOREIGN KEY (`area`)
    REFERENCES `PERSONAL`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LABORATORIO`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`Personal` (
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`),
  INDEX `fk_Personal_Cargo1_idx` (`cargo` ASC) VISIBLE,
  CONSTRAINT `fk_Personal_Cargo1`
    FOREIGN KEY (`cargo`)
    REFERENCES `PERSONAL`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LABORATORIO`.`Fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`Fecha` (
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LABORATORIO`.`Hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`Hora` (
  `hora` TIME NOT NULL,
  PRIMARY KEY (`hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LABORATORIO`.`Muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`Muestra` (
  `idMuestra` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `rutPersonal` VARCHAR(10) NOT NULL,
  `idTomaMuestra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMuestra`),
  INDEX `fk_Personal_has_PuntoMuestra_PuntoMuestra1_idx` (`idTomaMuestra` ASC) VISIBLE,
  INDEX `fk_Personal_has_PuntoMuestra_Personal1_idx` (`rutPersonal` ASC) VISIBLE,
  INDEX `fk_Muestra_Fecha1_idx` (`fecha` ASC) VISIBLE,
  INDEX `fk_Muestra_Hora1_idx` (`hora` ASC) VISIBLE,
  CONSTRAINT `fk_Personal_has_PuntoMuestra_Personal1`
    FOREIGN KEY (`rutPersonal`)
    REFERENCES `LABORATORIO`.`Personal` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_has_PuntoMuestra_PuntoMuestra1`
    FOREIGN KEY (`idTomaMuestra`)
    REFERENCES `LABORATORIO`.`PuntoMuestra` (`idPuntoMuestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Muestra_Fecha1`
    FOREIGN KEY (`fecha`)
    REFERENCES `LABORATORIO`.`Fecha` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Muestra_Hora1`
    FOREIGN KEY (`hora`)
    REFERENCES `LABORATORIO`.`Hora` (`hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LABORATORIO`.`Analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`Analisis` (
  `idAnalisis` VARCHAR(45) NOT NULL,
  `nombreAnalisis` VARCHAR(45) NOT NULL,
  `unidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAnalisis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LABORATORIO`.`ResultadoAnalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LABORATORIO`.`ResultadoAnalisis` (
  `idMuestra` VARCHAR(45) NULL,
  `idAnalisis` VARCHAR(45) NULL,
  `rutAnalista` VARCHAR(10) NULL,
  `resultado` DECIMAL(7,2) NULL,
  INDEX `fk_Analisis_Muestra1_idx` (`idMuestra` ASC) VISIBLE,
  INDEX `fk_ResultadoAnalisis_Analisis1_idx` (`idAnalisis` ASC) VISIBLE,
  INDEX `fk_ResultadoAnalisis_Personal1_idx` (`rutAnalista` ASC) VISIBLE,
  CONSTRAINT `fk_Analisis_Muestra1`
    FOREIGN KEY (`idMuestra`)
    REFERENCES `LABORATORIO`.`Muestra` (`idMuestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResultadoAnalisis_Analisis1`
    FOREIGN KEY (`idAnalisis`)
    REFERENCES `LABORATORIO`.`Analisis` (`idAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResultadoAnalisis_Personal1`
    FOREIGN KEY (`rutAnalista`)
    REFERENCES `LABORATORIO`.`Personal` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `PERSONAL` ;

-- -----------------------------------------------------
-- Table `PERSONAL`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSONAL`.`Personal` (
  `rut` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`),
  INDEX `fk_Personal_Cargo1_idx` (`cargo` ASC) VISIBLE,
  CONSTRAINT `fk_Personal_Cargo1`
    FOREIGN KEY (`cargo`)
    REFERENCES `PERSONAL`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `INSUMOS` ;

-- -----------------------------------------------------
-- Table `INSUMOS`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INSUMOS`.`Equipo` (
  `tag` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clase` VARCHAR(45) NOT NULL,
  `area` INT NOT NULL,
  PRIMARY KEY (`tag`),
  INDEX `fk_Equipo_ClaseEquipo_idx` (`clase` ASC) VISIBLE,
  INDEX `fk_Equipo_Area1_idx` (`area` ASC) VISIBLE,
  CONSTRAINT `fk_Equipo_ClaseEquipo`
    FOREIGN KEY (`clase`)
    REFERENCES `EQUIPOS`.`ClaseEquipo` (`clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Area1`
    FOREIGN KEY (`area`)
    REFERENCES `EQUIPOS`.`Area` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INSUMOS`.`Fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INSUMOS`.`Fecha` (
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INSUMOS`.`Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INSUMOS`.`Insumo` (
  `idInsumo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInsumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INSUMOS`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INSUMOS`.`Consumo` (
  `fecha` DATE NULL,
  `tag` VARCHAR(45) NULL,
  `insumo` VARCHAR(45) NULL,
  `valor` DECIMAL(7,2) NULL DEFAULT 0,
  `Consumocol` VARCHAR(45) NULL,
  PRIMARY KEY (`fecha`, `tag`, `insumo`),
  INDEX `fk_Consumo_Equipo1_idx` (`tag` ASC) VISIBLE,
  INDEX `fk_Consumo_Insumo1_idx` (`insumo` ASC) VISIBLE,
  CONSTRAINT `fk_Consumo_Fecha1`
    FOREIGN KEY (`fecha`)
    REFERENCES `INSUMOS`.`Fecha` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consumo_Equipo1`
    FOREIGN KEY (`tag`)
    REFERENCES `INSUMOS`.`Equipo` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consumo_Insumo1`
    FOREIGN KEY (`insumo`)
    REFERENCES `INSUMOS`.`Insumo` (`idInsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
